// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: songListProto/songList.songListProto

package songList

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for SongList service

func NewSongListEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for SongList service

type SongListService interface {
	Call(ctx context.Context, in *CallRequest, opts ...client.CallOption) (*CallResponse, error)
	ClientStream(ctx context.Context, opts ...client.CallOption) (SongList_ClientStreamService, error)
	ServerStream(ctx context.Context, in *ServerStreamRequest, opts ...client.CallOption) (SongList_ServerStreamService, error)
	BidiStream(ctx context.Context, opts ...client.CallOption) (SongList_BidiStreamService, error)
}

type songListService struct {
	c    client.Client
	name string
}

func NewSongListService(name string, c client.Client) SongListService {
	return &songListService{
		c:    c,
		name: name,
	}
}

func (c *songListService) Call(ctx context.Context, in *CallRequest, opts ...client.CallOption) (*CallResponse, error) {
	req := c.c.NewRequest(c.name, "SongList.Call", in)
	out := new(CallResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *songListService) ClientStream(ctx context.Context, opts ...client.CallOption) (SongList_ClientStreamService, error) {
	req := c.c.NewRequest(c.name, "SongList.ClientStream", &ClientStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &songListServiceClientStream{stream}, nil
}

type SongList_ClientStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Send(*ClientStreamRequest) error
}

type songListServiceClientStream struct {
	stream client.Stream
}

func (x *songListServiceClientStream) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *songListServiceClientStream) Close() error {
	return x.stream.Close()
}

func (x *songListServiceClientStream) Context() context.Context {
	return x.stream.Context()
}

func (x *songListServiceClientStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *songListServiceClientStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *songListServiceClientStream) Send(m *ClientStreamRequest) error {
	return x.stream.Send(m)
}

func (c *songListService) ServerStream(ctx context.Context, in *ServerStreamRequest, opts ...client.CallOption) (SongList_ServerStreamService, error) {
	req := c.c.NewRequest(c.name, "SongList.ServerStream", &ServerStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &songListServiceServerStream{stream}, nil
}

type SongList_ServerStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Recv() (*ServerStreamResponse, error)
}

type songListServiceServerStream struct {
	stream client.Stream
}

func (x *songListServiceServerStream) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *songListServiceServerStream) Close() error {
	return x.stream.Close()
}

func (x *songListServiceServerStream) Context() context.Context {
	return x.stream.Context()
}

func (x *songListServiceServerStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *songListServiceServerStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *songListServiceServerStream) Recv() (*ServerStreamResponse, error) {
	m := new(ServerStreamResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *songListService) BidiStream(ctx context.Context, opts ...client.CallOption) (SongList_BidiStreamService, error) {
	req := c.c.NewRequest(c.name, "SongList.BidiStream", &BidiStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &songListServiceBidiStream{stream}, nil
}

type SongList_BidiStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Send(*BidiStreamRequest) error
	Recv() (*BidiStreamResponse, error)
}

type songListServiceBidiStream struct {
	stream client.Stream
}

func (x *songListServiceBidiStream) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *songListServiceBidiStream) Close() error {
	return x.stream.Close()
}

func (x *songListServiceBidiStream) Context() context.Context {
	return x.stream.Context()
}

func (x *songListServiceBidiStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *songListServiceBidiStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *songListServiceBidiStream) Send(m *BidiStreamRequest) error {
	return x.stream.Send(m)
}

func (x *songListServiceBidiStream) Recv() (*BidiStreamResponse, error) {
	m := new(BidiStreamResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for SongList service

type SongListHandler interface {
	Call(context.Context, *CallRequest, *CallResponse) error
	ClientStream(context.Context, SongList_ClientStreamStream) error
	ServerStream(context.Context, *ServerStreamRequest, SongList_ServerStreamStream) error
	BidiStream(context.Context, SongList_BidiStreamStream) error
}

func RegisterSongListHandler(s server.Server, hdlr SongListHandler, opts ...server.HandlerOption) error {
	type songList interface {
		Call(ctx context.Context, in *CallRequest, out *CallResponse) error
		ClientStream(ctx context.Context, stream server.Stream) error
		ServerStream(ctx context.Context, stream server.Stream) error
		BidiStream(ctx context.Context, stream server.Stream) error
	}
	type SongList struct {
		songList
	}
	h := &songListHandler{hdlr}
	return s.Handle(s.NewHandler(&SongList{h}, opts...))
}

type songListHandler struct {
	SongListHandler
}

func (h *songListHandler) Call(ctx context.Context, in *CallRequest, out *CallResponse) error {
	return h.SongListHandler.Call(ctx, in, out)
}

func (h *songListHandler) ClientStream(ctx context.Context, stream server.Stream) error {
	return h.SongListHandler.ClientStream(ctx, &songListClientStreamStream{stream})
}

type SongList_ClientStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*ClientStreamRequest, error)
}

type songListClientStreamStream struct {
	stream server.Stream
}

func (x *songListClientStreamStream) Close() error {
	return x.stream.Close()
}

func (x *songListClientStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *songListClientStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *songListClientStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *songListClientStreamStream) Recv() (*ClientStreamRequest, error) {
	m := new(ClientStreamRequest)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (h *songListHandler) ServerStream(ctx context.Context, stream server.Stream) error {
	m := new(ServerStreamRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.SongListHandler.ServerStream(ctx, m, &songListServerStreamStream{stream})
}

type SongList_ServerStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*ServerStreamResponse) error
}

type songListServerStreamStream struct {
	stream server.Stream
}

func (x *songListServerStreamStream) Close() error {
	return x.stream.Close()
}

func (x *songListServerStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *songListServerStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *songListServerStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *songListServerStreamStream) Send(m *ServerStreamResponse) error {
	return x.stream.Send(m)
}

func (h *songListHandler) BidiStream(ctx context.Context, stream server.Stream) error {
	return h.SongListHandler.BidiStream(ctx, &songListBidiStreamStream{stream})
}

type SongList_BidiStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*BidiStreamResponse) error
	Recv() (*BidiStreamRequest, error)
}

type songListBidiStreamStream struct {
	stream server.Stream
}

func (x *songListBidiStreamStream) Close() error {
	return x.stream.Close()
}

func (x *songListBidiStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *songListBidiStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *songListBidiStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *songListBidiStreamStream) Send(m *BidiStreamResponse) error {
	return x.stream.Send(m)
}

func (x *songListBidiStreamStream) Recv() (*BidiStreamRequest, error) {
	m := new(BidiStreamRequest)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
